/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.*;
import Controlador.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author Pixel
 */
public class Vista extends javax.swing.JFrame {
    CtPlan CtPlan;
    CtCliente CtCliente;
    CtMascota CtMascota;
    CtPago CtPago;
    LinkedList<Cliente> clienteComboBox;
    LinkedList<Mascota> mascotaComboBox;
    LinkedList<Plan> planComboBox;
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.CtPlan = new CtPlan();
        this.CtCliente = new CtCliente();
        this.CtMascota = new CtMascota();
        this.CtPago = new CtPago();
        recargarComboBoxCliente();
        recargarComboBoxMascota();
        recargarComboBoxPlan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoPlan = new javax.swing.JTextField();
        nombrePlan = new javax.swing.JComboBox<>();
        precioPlan = new javax.swing.JTextField();
        btnCrearPlan = new javax.swing.JButton();
        btnConsultarPlan = new javax.swing.JButton();
        btnModificarPlan = new javax.swing.JButton();
        btnBorrarPlan = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        identificacionCliente = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        direccionCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        btnCrearCliente = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        btnLimpiarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        codigoMascota = new javax.swing.JTextField();
        nombreMascota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        annioNacMascota = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pesoMascota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clienteMascota = new javax.swing.JComboBox<>();
        btnCrearMascota = new javax.swing.JButton();
        btnConsultarMascota = new javax.swing.JButton();
        btnModificarMascota = new javax.swing.JButton();
        btnBorrarMascota = new javax.swing.JButton();
        btnLimpiarMascota = new javax.swing.JButton();
        especieMascota = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fechaPago = new javax.swing.JTextField();
        numCuotaPago = new javax.swing.JTextField();
        mascotaPago = new javax.swing.JComboBox<>();
        planPago = new javax.swing.JComboBox<>();
        btnCrearPago = new javax.swing.JButton();
        btnConsultarPago = new javax.swing.JButton();
        btnModificarPago = new javax.swing.JButton();
        btnBorrarPago = new javax.swing.JButton();
        btnLimpiarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        codigoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPlanActionPerformed(evt);
            }
        });

        nombrePlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienestar", "Elite", "Diamante" }));

        btnCrearPlan.setText("Crear");
        btnCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlanActionPerformed(evt);
            }
        });

        btnConsultarPlan.setText("Consultar");
        btnConsultarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPlanActionPerformed(evt);
            }
        });

        btnModificarPlan.setText("Modificar");
        btnModificarPlan.setEnabled(false);
        btnModificarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPlanActionPerformed(evt);
            }
        });

        btnBorrarPlan.setText("Borrar");
        btnBorrarPlan.setEnabled(false);
        btnBorrarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPlanActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoPlan)
                            .addComponent(nombrePlan, 0, 125, Short.MAX_VALUE)
                            .addComponent(precioPlan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearPlan)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarPlan)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPlan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarPlan)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPlan)
                    .addComponent(btnConsultarPlan)
                    .addComponent(btnModificarPlan)
                    .addComponent(btnBorrarPlan)
                    .addComponent(btnLimpiar))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Plan", jPanel1);

        jLabel4.setText("Identificación");

        jLabel5.setText("Nombres");

        jLabel6.setText("Apellidos");

        jLabel7.setText("Dirección");

        jLabel8.setText("Telefono");

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("Modificar");
        btnModificarCliente.setEnabled(false);
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnBorrarCliente.setText("Borrar");
        btnBorrarCliente.setEnabled(false);
        btnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteActionPerformed(evt);
            }
        });

        btnLimpiarCliente.setText("Limpiar");
        btnLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreCliente)
                            .addComponent(apellidoCliente)
                            .addComponent(direccionCliente)
                            .addComponent(telefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(identificacionCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCliente)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCliente)
                    .addComponent(btnConsultarCliente)
                    .addComponent(btnModificarCliente)
                    .addComponent(btnBorrarCliente)
                    .addComponent(btnLimpiarCliente))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        jLabel9.setText("Código");

        jLabel10.setText("Nombre");

        jLabel11.setText("Año de Nacimiento");

        jLabel12.setText("Peso");

        jLabel13.setText("Especie");

        jLabel14.setText("Cliente");

        clienteMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCrearMascota.setText("Crear");
        btnCrearMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMascotaActionPerformed(evt);
            }
        });

        btnConsultarMascota.setText("Consultar");
        btnConsultarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMascotaActionPerformed(evt);
            }
        });

        btnModificarMascota.setText("Modificar");
        btnModificarMascota.setEnabled(false);
        btnModificarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMascotaActionPerformed(evt);
            }
        });

        btnBorrarMascota.setText("Borrar");
        btnBorrarMascota.setEnabled(false);
        btnBorrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarMascotaActionPerformed(evt);
            }
        });

        btnLimpiarMascota.setText("Limpiar");
        btnLimpiarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMascotaActionPerformed(evt);
            }
        });

        especieMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canino", "Felino", "Reptil", "Ave", "Pez" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreMascota)
                                    .addComponent(annioNacMascota)
                                    .addComponent(pesoMascota)
                                    .addComponent(clienteMascota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(especieMascota, 0, 250, Short.MAX_VALUE))))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrearMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarMascota)
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(codigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annioNacMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(especieMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(clienteMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMascota)
                    .addComponent(btnConsultarMascota)
                    .addComponent(btnModificarMascota)
                    .addComponent(btnBorrarMascota)
                    .addComponent(btnLimpiarMascota))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Mascota", jPanel3);

        jLabel15.setText("Fecha Pago");

        jLabel16.setText("No. Cuota");

        jLabel17.setText("Mascota");

        jLabel18.setText("Plan");

        mascotaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        planPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCrearPago.setText("Crear");
        btnCrearPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPagoActionPerformed(evt);
            }
        });

        btnConsultarPago.setText("Consultar");
        btnConsultarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPagoActionPerformed(evt);
            }
        });

        btnModificarPago.setText("Modificar");
        btnModificarPago.setEnabled(false);

        btnBorrarPago.setText("Borrar");
        btnBorrarPago.setEnabled(false);

        btnLimpiarPago.setText("Limpiar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCrearPago)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaPago)
                            .addComponent(numCuotaPago)
                            .addComponent(mascotaPago, 0, 250, Short.MAX_VALUE)
                            .addComponent(planPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnConsultarPago)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPago)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarPago)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarPago)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(numCuotaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(mascotaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(planPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPago)
                    .addComponent(btnConsultarPago)
                    .addComponent(btnModificarPago)
                    .addComponent(btnBorrarPago)
                    .addComponent(btnLimpiarPago))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pago", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPlanActionPerformed

    private void btnCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlanActionPerformed
        String codigo = codigoPlan.getText();
        String nombre = nombrePlan.getSelectedItem().toString();
        int precio = Integer.parseInt(precioPlan.getText());
        Plan p = new Plan(codigo, nombre, precio);
        
        if(this.CtPlan.crearPlan(p)){
            JOptionPane.showMessageDialog(this, "El plan fue agregado en la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar el registro a la base de datos");
        }
        limpiarCampos();
        recargarComboBoxPlan();
    }//GEN-LAST:event_btnCrearPlanActionPerformed

    private void btnConsultarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPlanActionPerformed
        String codigo = codigoPlan.getText();
        Plan p = CtPlan.buscarPlan(codigo);
        if (p == null){
            JOptionPane.showMessageDialog(this, "El código de ese plan no fue encontrado");
            limpiarCampos();
        }else{
            if(p.getNombre().equals("Bienestar")){
                nombrePlan.setSelectedIndex(0);
            }else{
                if(p.getNombre().equals("Elite")){
                    nombrePlan.setSelectedIndex(1);
                }else{
                    nombrePlan.setSelectedIndex(2);
                }
            }
            precioPlan.setText(String.valueOf(p.getPrecio()));
            btnModificarPlan.setEnabled(true);
            btnBorrarPlan.setEnabled(true);
            btnCrearPlan.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnConsultarPlanActionPerformed

    private void btnModificarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPlanActionPerformed
        String codigo = codigoPlan.getText();
        String nombre = nombrePlan.getSelectedItem().toString();
        int precio = Integer.parseInt(precioPlan.getText());
        Plan p = new Plan(codigo, nombre, precio);
        try{
            boolean respuesta = CtPlan.actualizarPlan(p);
            if (respuesta){
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Registro no actualizado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Debe buscar el registro para actualizar");
        }
        limpiarCampos();
        recargarComboBoxPlan();
    }//GEN-LAST:event_btnModificarPlanActionPerformed

    private void btnBorrarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPlanActionPerformed
        String codigo = codigoPlan.getText();
        String nombre = nombrePlan.getSelectedItem().toString();
        int precio = Integer.parseInt(precioPlan.getText());
        Plan p = new Plan(codigo, nombre, precio);
        try{
            boolean respuesta = CtPlan.borrarPlan(p);
            if (respuesta){
                JOptionPane.showMessageDialog(this, "Registro borrado correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Registro no borrado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se pudo borrar el registro");
        }
        limpiarCampos();
        recargarComboBoxPlan();
        
        /*String codigo = codigoPlan.getText();
        if(this.CtPlan.borrarPlan(codigo)){
            JOptionPane.showMessageDialog(this, "El plan fue barrado de la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo borrar el Plan de la base de datos");
        }
        limpiarCampos();*/
    }//GEN-LAST:event_btnBorrarPlanActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        String identificion = identificacionCliente.getText();
        String nombres = nombreCliente.getText();
        String apellidos = apellidoCliente.getText();
        String direccion = direccionCliente.getText();
        String telefono = telefonoCliente.getText();
        Cliente c = new Cliente(identificion, nombres, apellidos, direccion, telefono);
        if (this.CtCliente.crearCliente(c)){
            JOptionPane.showMessageDialog(this, "El Cliente fue agregado a la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar el Cliente a la base de datos");
        }
        limpiarClientes();
        recargarComboBoxCliente();
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void btnLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarClienteActionPerformed
        limpiarClientes();
    }//GEN-LAST:event_btnLimpiarClienteActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        String identificacion = identificacionCliente.getText();
        Cliente c = CtCliente.buscarCliente(identificacion);
        if (c == null){
            JOptionPane.showMessageDialog(this, "La identificacion del Cliente no fue encontrado");
            limpiarClientes();
        }else{
            nombreCliente.setText(String.valueOf(c.getNombre()));
            apellidoCliente.setText(String.valueOf(c.getApellido()));
            direccionCliente.setText(String.valueOf(c.getDireccion()));
            telefonoCliente.setText(String.valueOf(c.getTelefono()));
            btnModificarCliente.setEnabled(true);
            btnBorrarCliente.setEnabled(true);
        }
        btnModificarCliente.setEnabled(true);
        btnBorrarCliente.setEnabled(true);
        btnCrearCliente.setEnabled(false);
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        String identificacion = identificacionCliente.getText();
        String nombres = nombreCliente.getText();
        String apellidos = apellidoCliente.getText();
        String direccion = direccionCliente.getText();
        String telefono = telefonoCliente.getText();
        Cliente c = new Cliente(identificacion, nombres, apellidos, direccion, telefono);
        try{
            boolean respuesta = CtCliente.actualizarCliente(c);
            if (respuesta){
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Registro no actualizado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Debe buscar el registro para actualizar");
        }
        limpiarClientes();
        recargarComboBoxCliente();
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteActionPerformed
        String identificacion = identificacionCliente.getText();
        String nombres = nombreCliente.getText();
        String apellidos = apellidoCliente.getText();
        String direccion = direccionCliente.getText();
        String telefono = telefonoCliente.getText();
        Cliente c = new Cliente(identificacion, nombres, apellidos, direccion, telefono);
        try{
            boolean respuesta = CtCliente.borrarCliente(c);
            if (respuesta){
                JOptionPane.showMessageDialog(this, "Registro borrado correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Registro no borrado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se pudo borrar el registro");
        }
        limpiarClientes();
        recargarComboBoxCliente();
    }//GEN-LAST:event_btnBorrarClienteActionPerformed

    private void btnConsultarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMascotaActionPerformed
        String codigo = codigoMascota.getText();
        Mascota m = CtMascota.buscarMascota(codigo);
        if (m == null){
            JOptionPane.showMessageDialog(this, "El Codigo de la Mascota no fue encontrado");
            limpiarMascota();
        }else{
            nombreMascota.setText(String.valueOf(m.getNombre()));
            annioNacMascota.setText(String.valueOf(m.getAnnioNac()));
            pesoMascota.setText(String.valueOf(m.getPeso()));
            if(m.getEspecie().equals("Canino")){
                especieMascota.setSelectedIndex(0);
            }else{
                especieMascota.setSelectedIndex(1); 
            }
            int indice = 0;
            System.out.println("El id del Cliente es: "+m.getIdCliente());
            for (Cliente cl:clienteComboBox){
                if (cl.getIdPK()==m.getIdCliente()){
                    clienteMascota.setSelectedIndex(indice);
                }
                indice++;
            }
            //clienteMascota.setSelectedItem(m.getIdCliente());
            //telefonoClie.setText(String.valueOf(c.getTelefono()));
            btnModificarMascota.setEnabled(true);
            btnBorrarMascota.setEnabled(true);
            btnCrearMascota.setEnabled(false);
        }
    }//GEN-LAST:event_btnConsultarMascotaActionPerformed

    private void btnCrearMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMascotaActionPerformed
        String codigo = codigoMascota.getText();
        String nombre = nombreMascota.getText();
        int annioNac = Integer.parseInt(annioNacMascota.getText());
        int peso = Integer.parseInt(pesoMascota.getText());
        String especie = especieMascota.getSelectedItem().toString();
        //int idPKCliente = CtCliente.obtenerIdPKClienteComboBox(clienteComboBox, clienteMascota);
        String clienteSeleccionado = clienteMascota.getSelectedItem().toString();
        int primerEspacio = clienteSeleccionado.indexOf(" ");
        int idFkCliente = Integer.parseInt(clienteSeleccionado.substring(0, primerEspacio));
        Mascota m = new Mascota(codigo, nombre, annioNac, peso, especie, idFkCliente);
        if (this.CtMascota.crearMascota(m)){
            JOptionPane.showMessageDialog(this, "La Mascota fue agregada a la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar la Mascota a la base de datos");
        }
        limpiarMascota();
        recargarComboBoxMascota();
    }//GEN-LAST:event_btnCrearMascotaActionPerformed

    
    
    private void btnLimpiarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMascotaActionPerformed
        limpiarMascota();
    }//GEN-LAST:event_btnLimpiarMascotaActionPerformed

    private void btnModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMascotaActionPerformed
        String codigo = codigoMascota.getText();
        String nombre = nombreMascota.getText();
        int annioNac = Integer.parseInt(annioNacMascota.getText());
        int peso = Integer.parseInt(pesoMascota.getText());
        String especie = especieMascota.getSelectedItem().toString();
        String clienteSeleccionado = clienteMascota.getSelectedItem().toString();
        int primerEspacio = clienteSeleccionado.indexOf(" ");
        int idFkCliente = Integer.parseInt(clienteSeleccionado.substring(0, primerEspacio));
        Mascota m = new Mascota(codigo, nombre, annioNac, peso, especie, idFkCliente);
        if (this.CtMascota.modificarMascota(m)){
            JOptionPane.showMessageDialog(this, "La Mascota fue modificada en la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar la Mascota en la base de datos");
        }
        limpiarMascota();
        recargarComboBoxMascota();
    }//GEN-LAST:event_btnModificarMascotaActionPerformed

    private void btnCrearPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPagoActionPerformed
        String fecha = fechaPago.getText();
        int cuota = Integer.parseInt(numCuotaPago.getText());
        String mascotaSeleccionada = mascotaPago.getSelectedItem().toString();
        int primerEspacio = mascotaSeleccionada.indexOf(" ");
        int idFkMascota = Integer.parseInt(mascotaSeleccionada.substring(0, primerEspacio));
        String planSeleccionado = planPago.getSelectedItem().toString();
        int primerEsp = planSeleccionado.indexOf(" ");
        int idFkPlan = Integer.parseInt(planSeleccionado.substring(0, primerEsp));
        Pago p = new Pago(fecha, cuota, idFkMascota, idFkPlan);
        if (this.CtPago.crearPago(p)){
            JOptionPane.showMessageDialog(this, "El Pago fue agregado a la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar el Pago a la base de datos");
        }
        limpiarPago();
    }//GEN-LAST:event_btnCrearPagoActionPerformed

    private void btnBorrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarMascotaActionPerformed
        String codigo = codigoMascota.getText();
        String nombre = nombreMascota.getText();
        int annioNac = Integer.parseInt(annioNacMascota.getText());
        int peso = Integer.parseInt(pesoMascota.getText());
        String especie = especieMascota.getSelectedItem().toString();
        String clienteSeleccionado = clienteMascota.getSelectedItem().toString();
        int primerEspacio = clienteSeleccionado.indexOf(" ");
        int idFkCliente = Integer.parseInt(clienteSeleccionado.substring(0, primerEspacio));
        Mascota m = new Mascota(codigo, nombre, annioNac, peso, especie, idFkCliente);
        if (this.CtMascota.borrarMascota(m)){
            JOptionPane.showMessageDialog(this, "La Mascota fue borrada de la base de datos");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo borrar la Mascota de la base de datos");
        }
        limpiarMascota();
        recargarComboBoxMascota();
    }//GEN-LAST:event_btnBorrarMascotaActionPerformed

    private void btnConsultarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPagoActionPerformed
        String mascotaSeleccionada = mascotaPago.getSelectedItem().toString();
        int primerEspacio = mascotaSeleccionada.indexOf(" ");
        int idFkMascota = Integer.parseInt(mascotaSeleccionada.substring(0, primerEspacio));
        int cuota = Integer.parseInt(numCuotaPago.getText());
        System.out.println(idFkMascota+" - "+ cuota);
        Pago p = CtPago.buscarPago(cuota, idFkMascota);    
        if (p == null){
            JOptionPane.showMessageDialog(this, "El Pago no fue encontrado");
            limpiarPago();
        }else{
            fechaPago.setText(String.valueOf(p.getFechaPago()));
            int indice = 0;
            //System.out.println("El id del Cliente es: "+m.getIdCliente());
            for (Plan pl:planComboBox){
                if (pl.getIdPK()==p.getIdPlan()){
                    planPago.setSelectedIndex(indice);
                }
                indice++;
            }
            //clienteMascota.setSelectedItem(m.getIdCliente());
            //telefonoClie.setText(String.valueOf(c.getTelefono()));
            btnModificarPago.setEnabled(true);
            btnBorrarPago.setEnabled(true);
            btnCrearPago.setEnabled(false);
        }
    }//GEN-LAST:event_btnConsultarPagoActionPerformed

    private void limpiarCampos(){
        codigoPlan.setText("");
        precioPlan.setText("");
        btnModificarPlan.setEnabled(false);
        btnBorrarPlan.setEnabled(false);
        btnCrearPlan.setEnabled(true);
    }
    
    private void limpiarClientes(){
        identificacionCliente.setText("");
        nombreCliente.setText("");
        apellidoCliente.setText("");
        direccionCliente.setText("");
        telefonoCliente.setText("");
        btnModificarCliente.setEnabled(false);
        btnBorrarCliente.setEnabled(false);
        btnCrearCliente.setEnabled(true);
    }
    
    private void limpiarMascota(){
        codigoMascota.setText("");
        nombreMascota.setText("");
        annioNacMascota.setText("");
        pesoMascota.setText("");
        especieMascota.setSelectedIndex(0);
        clienteMascota.setSelectedIndex(0);
        btnModificarMascota.setEnabled(false);
        btnBorrarMascota.setEnabled(false);
        btnCrearMascota.setEnabled(true);
    }
    
    private void limpiarPago(){
        fechaPago.setText("");
        numCuotaPago.setText("");
        mascotaPago.setSelectedIndex(0);
        planPago.setSelectedIndex(0);
        btnModificarPago.setEnabled(false);
        btnBorrarPago.setEnabled(false);
        btnCrearPago.setEnabled(true);
    }
    
    private void recargarComboBoxCliente(){
        clienteMascota.removeAllItems();
        this.clienteComboBox = CtCliente.listarTodosClientes();
        int contador = 0;
        while(contador < clienteComboBox.size()){
            String tempNombre;
            tempNombre = clienteComboBox.get(contador).getIdPK() + " - " + clienteComboBox.get(contador).getIdentificacion() + " - " + clienteComboBox.get(contador).getNombre() + " " + clienteComboBox.get(contador).getApellido();
            clienteMascota.addItem(tempNombre);
            contador = contador+1;
        }
    }
    
    private void recargarComboBoxMascota(){
        mascotaPago.removeAllItems();
        this.mascotaComboBox = CtMascota.listarTodasMascotas();
        int contador = 0;
        while(contador < mascotaComboBox.size()){
            String tempNombre;
            tempNombre = mascotaComboBox.get(contador).getIdPK() + " - " + mascotaComboBox.get(contador).getCodigo() + " - " + mascotaComboBox.get(contador).getNombre();
            mascotaPago.addItem(tempNombre);
            contador = contador+1;
        }
    }
    
    private void recargarComboBoxPlan(){
        planPago.removeAllItems();
        this.planComboBox = CtPlan.listarTodosPlanes();
        int contador = 0;
        while(contador < planComboBox.size()){
            String tempNombre;
            tempNombre = planComboBox.get(contador).getIdPK() + " - " + planComboBox.get(contador).getNombre() + " - " + planComboBox.get(contador).getPrecio();
            planPago.addItem(tempNombre);
            contador = contador+1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annioNacMascota;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnBorrarMascota;
    private javax.swing.JButton btnBorrarPago;
    private javax.swing.JButton btnBorrarPlan;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarMascota;
    private javax.swing.JButton btnConsultarPago;
    private javax.swing.JButton btnConsultarPlan;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearMascota;
    private javax.swing.JButton btnCrearPago;
    private javax.swing.JButton btnCrearPlan;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarCliente;
    private javax.swing.JButton btnLimpiarMascota;
    private javax.swing.JButton btnLimpiarPago;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarMascota;
    private javax.swing.JButton btnModificarPago;
    private javax.swing.JButton btnModificarPlan;
    private javax.swing.JComboBox<String> clienteMascota;
    private javax.swing.JTextField codigoMascota;
    private javax.swing.JTextField codigoPlan;
    private javax.swing.JTextField direccionCliente;
    private javax.swing.JComboBox<String> especieMascota;
    private javax.swing.JTextField fechaPago;
    private javax.swing.JTextField identificacionCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> mascotaPago;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField nombreMascota;
    private javax.swing.JComboBox<String> nombrePlan;
    private javax.swing.JTextField numCuotaPago;
    private javax.swing.JTextField pesoMascota;
    private javax.swing.JComboBox<String> planPago;
    private javax.swing.JTextField precioPlan;
    private javax.swing.JTextField telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
